pid logs/sitio1.pid;
events {
	worker_connections 1024;
}
http {
	server {
		listen 81;
	location / {
		root /mnt/c/Users/jluca/OneDrive/Desktop/DesWeb/17349/nginx/3sitios/sitio1;
		index index.html;
		}
	}
}
